name: Docker Publish

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: azure/docker-login@v1
    - name: Login
    - with:
        login-server: ghcr.io
        username: $GITHUB_ACTOR
        password: ${{ secrets.GITHUB_TOKEN }} 
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/buildtheearth/netlify-cms-auth:$(git rev-parse --short HEAD) --tag ghcr.io/buildtheearth/netlify-cms-auth:latest
    - name: Docker push tag
      run: docker push ghcr.io/buildtheearth/netlify-cms-auth:$(git rev-parse --short HEAD)
    - name: Docker push latest
      run: docker push ghcr.io/buildtheearth/netlify-cms-auth:latest
